[package]
name = "paswitch-rs"
version = "0.3.4"
authors = ["Robert Plant <rob@robertplant.io>"]
edition = "2021"
description = "List and swap to pulse sinks by name"
license = "GPL-3.0-only"
repository = "https://github.com/RobertPlant/paswitch-rs/"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
regex = "1.6.0"
strum = "0.24.1"
strum_macros = "0.24"
term = "0.7.0"
exitfailure = "0.5.1"
