[package]
name = "paswitch-rs"
version = "0.1.0"
authors = ["Robert Plant <rob@robertplant.io>"]
edition = "2018"
description = "List and swap to pulse sinks by name"
license = "GPL-3.0-only"
repository = "https://github.com/RobertPlant/paswitch-rs/"

[dependencies]
regex = "1.4.3"
quicli = "0.4.0"
structopt = "0.3.21"
term = "0.7.0"
strum = "0.20"
strum_macros = "0.20"

