[package]
name = "paswitch-rs"
version = "0.3.12"
authors = ["Robert Plant <rob@robertplant.io>"]
edition = "2021"
description = "List and swap to pulse sinks by name"
license = "GPL-3.0-only"
repository = "https://github.com/RobertPlant/paswitch-rs/"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
regex = "1.10.4"
strum = "0.26.2"
strum_macros = "0.26.2"
term = "0.7.0"
exitfailure = "0.5.1"
