[package]
name = "paswitch-rs"
version = "0.3.1"
authors = ["Robert Plant <rob@robertplant.io>"]
edition = "2021"
description = "List and swap to pulse sinks by name"
license = "GPL-3.0-only"
repository = "https://github.com/RobertPlant/paswitch-rs/"

[dependencies]
quicli = "0.4.0"
regex = "1.5.6"
structopt = "0.3.26"
strum = "0.24.0"
strum_macros = "0.24"
term = "0.7.0"
